---
swagger: "2.0"
info:
  description: "No description"
  version: "1.0.0"
  title: "navatic"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /login:
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /register:
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /news:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
  /categories:
    get:
      parameters: []
      responses:
        200:
          description: "Status 200"
  /events:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      - name: "city"
        in: "query"
        required: false
        type: "string"
      - name: "place"
        in: "query"
        required: false
        type: "string"
      - name: "category"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
  /event/{eid}/sans:
    get:
      parameters:
      - name: "city"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "eid"
      in: "path"
      required: true
      type: "string"
  /places:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
  /subscribe:
    post:
      parameters: []
      responses:
        200:
          description: "Status 200"
  /advertises:
    get:
      parameters: []
      responses:
        200:
          description: "Status 200"
  /verify:
    post:
      parameters: []
      responses:
        200:
          description: "Status 200"
  /cities:
    get:
      parameters: []
      responses:
        200:
          description: "Status 200"
  /event/{eid}:
    get:
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "eid"
      in: "path"
      required: true
      type: "string"
  /{oid}/redirect:
    post:
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "status"
        in: "formData"
        required: false
        type: "number"
      - name: "transId"
        in: "formData"
        required: false
        type: "number"
      - name: "factorNumber"
        in: "formData"
        required: false
        type: "number"
      - name: "cardNumber"
        in: "formData"
        required: false
        type: "number"
      - name: "message"
        in: "formData"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "oid"
      in: "path"
      required: true
      type: "string"
  /admin/users:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
  /admin/user/{uid}:
    get:
      summary: "get user by phone number"
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "uid"
      in: "path"
      required: true
      type: "string"
  /admin/sans/{sid}/tickets:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "sid"
      in: "path"
      required: true
      type: "string"
  /admin/category:
    get:
      parameters:
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /admin/category/{cid}:
    delete:
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "cid"
      in: "path"
      required: true
      type: "string"
  /admin/advertise:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /admin/advertise/{aid}:
    delete:
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "aid"
      in: "path"
      required: true
      type: "string"
  /admin/news:
    get:
      parameters:
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /admin/news/{nid}:
    delete:
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "nid"
      in: "path"
      required: true
      type: "string"
  /admin/event:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    post:
      parameters: []
      responses:
        200:
          description: "Status 200"
  /admin/event/{eid}:
    delete:
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "eid"
      in: "path"
      required: true
      type: "string"
  /admin/place:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenumber"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /admin/place/{pid}:
    delete:
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "pid"
      in: "path"
      required: true
      type: "string"
  /admin/payment/rollback:
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /admin/sans/{sid}/orders:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "sid"
      in: "path"
      required: true
      type: "string"
  /admin/sans:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /admin/sans/{sid}:
    get:
      summary: "single sans status"
      parameters: []
      responses:
        200:
          description: "Status 200"
    delete:
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "sid"
      in: "path"
      required: true
      type: "string"
  /admin/city:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /admin/city/{cid}:
    delete:
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "cid"
      in: "path"
      required: true
      type: "string"
  /admin/state:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /admin/state/{sid}:
    delete:
      parameters: []
      responses:
        200:
          description: "Status 200"
    patch:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "sid"
      in: "path"
      required: true
      type: "string"
  /admin/event/{eid}/sans:
    get:
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "eid"
      in: "path"
      required: true
      type: "string"
  /user/{uid}/payments:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "uid"
      in: "path"
      required: true
      type: "string"
  /user/{uid}/tickets:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "number"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "uid"
      in: "path"
      required: true
      type: "string"
  /user/{uid}/orders:
    get:
      parameters:
      - name: "pagesize"
        in: "query"
        required: false
        type: "number"
      - name: "pagenum"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "uid"
      in: "path"
      required: true
      type: "string"
  /user/{uid}/order:
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "uid"
      in: "path"
      required: true
      type: "string"
  /user/order/{oid}/pay:
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "oid"
      in: "path"
      required: true
      type: "string"
  /user/{uid}/order/{oid}/tickets:
    get:
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "uid"
      in: "path"
      required: true
      type: "string"
    - name: "oid"
      in: "path"
      required: true
      type: "string"
  /user/{uid}/renderpdf:
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "uid"
      in: "path"
      required: true
      type: "string"
  /event/{eid}/sans/{sid}/place/{pid}:
    get:
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "eid"
      in: "path"
      required: true
      type: "string"
    - name: "sid"
      in: "path"
      required: true
      type: "string"
    - name: "pid"
      in: "path"
      required: true
      type: "string"
  /supervisor/sans/{sid}/tickets:
    get:
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "sid"
      in: "path"
      required: true
      type: "string"
  /supervisor/ticket/verify:
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
  /supervisor/ticket/enter:
    post:
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
      responses:
        200:
          description: "Status 200"
